# Use root/example as user/password credentials
version: "3.3"

services:
  mongo:
    image: mongo
    container_name: thethe_mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: thethe

    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb_data:/data/db

  redis:
    image: redis
    container_name: thethe_redis
    restart: always
    ports:
      - 6379:6379

  celery:
    build: .
    container_name: thethe_celery
    command: /usr/local/bin/watchmedo auto-restart -d tasks -p '*.py' -- celery -A tasks.tasks:celery_app worker -l info
    volumes:
      - ./server:/usr/src/thethe/server
      - ./tasks:/usr/src/thethe/tasks
      - ./frontend/public/static/phishtank:/temp/phishtank
    depends_on:
      - redis

  server:
    build: .
    container_name: thethe_server
    command: >
      sh -c "python server/register_plugins.py && /usr/local/bin/gunicorn server.main:app -w 4 -t 90 --log-level=debug -b 0.0.0.0:8000 --reload"
    volumes:
      - ./server:/usr/src/thethe/server
      - ./tasks:/usr/src/thethe/tasks
      - ./frontend/public/static/phishtank:/temp/phishtank
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - celery
