version: "3.3"

services:
  mongo:
    image: mongo
    container_name: thethe_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: thethe
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - ./mongodb_data/:/data/db

  redis:
    image: redis
    container_name: thethe_redis
    restart: always

  celery:
    build:
      context: https://github.com/ElevenPaths/thethe_server.git
    container_name: thethe_celery
    command: /usr/local/bin/celery -A tasks.tasks:celery_app worker --concurrency 1 -l info
    volumes:
      - ./external/phishtank:/temp/phishtank
    depends_on:
      - redis

  frontend:
    build:
      context: https://github.com/ElevenPaths/thethe_frontend.git
    container_name: thethe_frontend
    volumes:
      - ./external/phishtank:/usr/share/nginx/html/static/phishtank
    ports:
      - 80:80
      - 443:443
    depends_on:
      - server

  server:
    build:
      context: https://github.com/ElevenPaths/thethe_server.git
    container_name: thethe_server
    command: >
      sh -c "python server/register_plugins.py &&
      /usr/local/bin/gunicorn server.main:app -w 4 -t 90 --log-level=info -b 0.0.0.0:8000"
    volumes:
      - ./external/phishtank:/temp/phishtank
    depends_on:
      - mongo
      - celery
