version: "3.3"

services:
  mongo:
    image: mongo
    container_name: thethe_mongo
    ports:
      - 27017:27017
    env_file: .env
    volumes:
      - ./mongodb_data:/data/db

  redis:
    image: redis
    container_name: thethe_redis
    ports:
      - 6379:6379

  celery:
    build:
      context: thethe_server/
    env_file: .env
    container_name: thethe_celery
    command: /usr/local/bin/watchmedo auto-restart -d ./tasks -p '*.py' -- celery -A tasks.tasks:celery_app worker --concurrency 1 -l info
    volumes:
      - ./thethe_server/server:/usr/src/thethe/server
      - ./thethe_server/tasks:/usr/src/thethe/tasks
      - ./external/phishtank:/temp/phishtank
      - ./external/urlscan:/temp/urlscan
    depends_on:
      - redis

  server:
    build:
      context: thethe_server/
    env_file: .env
    container_name: thethe_server
    command: >
      sh -c "python server/register_plugins.py && /usr/local/bin/gunicorn server.main:app -w 4 -t 90 --log-level=info -b 0.0.0.0:8000 --reload"
    volumes:
      - ./thethe_server/server:/usr/src/thethe/server
      - ./thethe_server/tasks:/usr/src/thethe/tasks
      - ./external/phishtank:/temp/phishtank
      - ./external/urlscan:/temp/urlscan
    ports:
      - 8000:8000
    depends_on:
      - mongo
      - celery
